name: 'Upkeep Docs'
description: 'Automated documentation generation using GitHub Copilot CLI and GitHub Coding Agent'
author: 'Ashley Childress'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  custom-config:
    description: 'Path to custom configuration file (optional)'
    required: false

outputs:
  triggered:
    description: 'Whether the coding agent was successfully triggered'
  timestamp:
    description: 'Timestamp when the coding agent was triggered'

runs:
  using: 'node22'
  main: 'src/main.js'
